{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "run_frontend_in_colab.ipynb",
      "provenance": [],
      "collapsed_sections": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "source": [
        "# download nltk stopwords\n",
        "import nltk\n",
        "nltk.download('stopwords')"
      ],
      "metadata": {
        "id": "bCPDHP7zTQJZ",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "b66b6fde-a6d8-486b-9796-8ee16cc3241e"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "[nltk_data] Downloading package stopwords to /root/nltk_data...\n",
            "[nltk_data]   Unzipping corpora/stopwords.zip.\n"
          ]
        },
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "True"
            ]
          },
          "metadata": {},
          "execution_count": 1
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# Install a particular version of `google-cloud-storage` because (oddly enough) \n",
        "# the  version on Colab and GCP is old. A dependency error below is okay.\n",
        "!pip install -q google-cloud-storage==1.43.0"
      ],
      "metadata": {
        "id": "lAt6KT8xOgHH",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "11617324-a522-40ee-ac9e-b5e23baf87ae"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\u001b[K     |████████████████████████████████| 106 kB 7.8 MB/s \n",
            "\u001b[K     |████████████████████████████████| 75 kB 3.3 MB/s \n",
            "\u001b[K     |████████████████████████████████| 111 kB 55.3 MB/s \n",
            "\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
            "google-cloud-translate 1.5.0 requires google-api-core[grpc]<2.0.0dev,>=1.6.0, but you have google-api-core 2.4.0 which is incompatible.\n",
            "google-cloud-translate 1.5.0 requires google-cloud-core<2.0dev,>=1.0.0, but you have google-cloud-core 2.2.1 which is incompatible.\n",
            "google-cloud-language 1.2.0 requires google-api-core[grpc]<2.0.0dev,>=1.6.0, but you have google-api-core 2.4.0 which is incompatible.\n",
            "google-cloud-firestore 1.7.0 requires google-api-core[grpc]<2.0.0dev,>=1.14.0, but you have google-api-core 2.4.0 which is incompatible.\n",
            "google-cloud-firestore 1.7.0 requires google-cloud-core<2.0dev,>=1.0.3, but you have google-cloud-core 2.2.1 which is incompatible.\n",
            "google-cloud-datastore 1.8.0 requires google-api-core[grpc]<2.0.0dev,>=1.6.0, but you have google-api-core 2.4.0 which is incompatible.\n",
            "google-cloud-datastore 1.8.0 requires google-cloud-core<2.0dev,>=1.0.0, but you have google-cloud-core 2.2.1 which is incompatible.\n",
            "google-cloud-bigquery 1.21.0 requires google-cloud-core<2.0dev,>=1.0.3, but you have google-cloud-core 2.2.1 which is incompatible.\n",
            "google-cloud-bigquery 1.21.0 requires google-resumable-media!=0.4.0,<0.5.0dev,>=0.3.1, but you have google-resumable-media 2.1.0 which is incompatible.\n",
            "google-cloud-bigquery-storage 1.1.0 requires google-api-core[grpc]<2.0.0dev,>=1.14.0, but you have google-api-core 2.4.0 which is incompatible.\n",
            "google-api-python-client 1.12.8 requires google-api-core<2dev,>=1.21.0, but you have google-api-core 2.4.0 which is incompatible.\n",
            "firebase-admin 4.4.0 requires google-api-core[grpc]<2.0.0dev,>=1.14.0; platform_python_implementation != \"PyPy\", but you have google-api-core 2.4.0 which is incompatible.\u001b[0m\n",
            "\u001b[?25h"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        " authenticate below for Google Storage access as needed\n",
        "from google.colab import auth\n",
        "auth.authenticate_user()"
      ],
      "metadata": {
        "id": "-oKFly5jFLFn",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "83ee08ff-a649-4b56-974e-c1e699e3b43c"
      },
      "execution_count": 3,
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Go to the following link in your browser:\n",
            "\n",
            "    https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=32555940559.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fappengine.admin+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcompute+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Faccounts.reauth+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&state=03d0QDKpDG4mUoXMBcTJC2gQkzxMLA&prompt=consent&access_type=offline&code_challenge=eoDKfES1MBMgEcWGl4AjX3TOaOqQWCnwaXAkq3wWDdg&code_challenge_method=S256\n",
            "\n",
            "Enter verification code: 4/1AX4XfWg76wMiOYtB9deWsKd5Hk4FojKIw87RnpgcUtMF5Z_-o3j6vfcr_S0\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# install ngrok to emulate public IP / address\n",
        "!wget -N https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -O ngrok-stable-linux-amd64.zip\n",
        "!unzip -u ngrok-stable-linux-amd64.zip"
      ],
      "metadata": {
        "id": "FrBdFNYgiyab",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "f4ad3159-6e57-41bd-8b05-c979e17d3ab6"
      },
      "execution_count": 4,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "WARNING: timestamping does nothing in combination with -O. See the manual\n",
            "for details.\n",
            "\n",
            "--2022-01-12 10:12:25--  https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip\n",
            "Resolving bin.equinox.io (bin.equinox.io)... 18.205.222.128, 52.202.168.65, 54.161.241.46, ...\n",
            "Connecting to bin.equinox.io (bin.equinox.io)|18.205.222.128|:443... connected.\n",
            "HTTP request sent, awaiting response... 200 OK\n",
            "Length: 13832437 (13M) [application/octet-stream]\n",
            "Saving to: ‘ngrok-stable-linux-amd64.zip’\n",
            "\n",
            "ngrok-stable-linux- 100%[===================>]  13.19M  3.38MB/s    in 5.1s    \n",
            "\n",
            "2022-01-12 10:12:31 (2.59 MB/s) - ‘ngrok-stable-linux-amd64.zip’ saved [13832437/13832437]\n",
            "\n",
            "Archive:  ngrok-stable-linux-amd64.zip\n",
            "  inflating: ngrok                   \n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# TODO: sign up for an ngrok account\n",
        "# then put your ngrok token below, uncomment, and execute\n",
        "!./ngrok authtoken 23QJn9gavUiv7HxL8GyEiMRcvpf_6pNYscMASov2UucrAjqDv"
      ],
      "metadata": {
        "id": "xA-_dKEZbsXW",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "f91deb48-a561-408f-8e16-fcbb26bf8c61"
      },
      "execution_count": 5,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Authtoken saved to configuration file: /root/.ngrok2/ngrok.yml\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 12,
      "metadata": {
        "id": "nXn5PlyGORQr",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "75f04dc7-7043-483d-be0f-0f9f6d5bf546"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Collecting pyspark\n",
            "  Downloading pyspark-3.2.0.tar.gz (281.3 MB)\n",
            "\u001b[K     |████████████████████████████████| 281.3 MB 23 kB/s \n",
            "\u001b[?25hCollecting py4j==0.10.9.2\n",
            "  Downloading py4j-0.10.9.2-py2.py3-none-any.whl (198 kB)\n",
            "\u001b[K     |████████████████████████████████| 198 kB 43.8 MB/s \n",
            "\u001b[?25hBuilding wheels for collected packages: pyspark\n",
            "  Building wheel for pyspark (setup.py) ... \u001b[?25l\u001b[?25hdone\n",
            "  Created wheel for pyspark: filename=pyspark-3.2.0-py2.py3-none-any.whl size=281805911 sha256=495f0ca06ec77a9643a0778f9ea9c9acb8571f857e12fbe3b242f96465294535\n",
            "  Stored in directory: /root/.cache/pip/wheels/0b/de/d2/9be5d59d7331c6c2a7c1b6d1a4f463ce107332b1ecd4e80718\n",
            "Successfully built pyspark\n",
            "Installing collected packages: py4j, pyspark\n",
            "Successfully installed py4j-0.10.9.2 pyspark-3.2.0\n"
          ]
        }
      ],
      "source": [
        "# install a ngrok python package and a version of flask that works with it in \n",
        "# colab\n",
        "!pip -q install flask-ngrok\n",
        "!pip -q install flask==0.12.2\n",
        "# !pip -q install flask_restful\n",
        "\n",
        "# install things we need:\n",
        "!pip install pyspark"
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "# Run the app"
      ],
      "metadata": {
        "id": "6dW0y91OVu5J"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "# you need to upload your implementation of search_app.py\n",
        "import search_frontend as se"
      ],
      "metadata": {
        "id": "7opNkV6uRHIv",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "48c7996a-a757-473e-abc1-a87375ecf0e5"
      },
      "execution_count": 9,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "[nltk_data] Downloading package stopwords to /root/nltk_data...\n",
            "[nltk_data]   Package stopwords is already up-to-date!\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# uncomment the code below and execute to reload the module when you make \n",
        "# changes to search_frontend.py (after you upload again).\n",
        "import importlib\n",
        "importlib.reload(se)"
      ],
      "metadata": {
        "id": "oTGXXYEXV5l8",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "ec6afe3e-6644-4234-edb9-e52e56e72b06"
      },
      "execution_count": 35,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "[nltk_data] Downloading package stopwords to /root/nltk_data...\n",
            "[nltk_data]   Package stopwords is already up-to-date!\n"
          ]
        },
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "<module 'search_frontend' from '/content/search_frontend.py'>"
            ]
          },
          "metadata": {},
          "execution_count": 35
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "from flask_ngrok import run_with_ngrok\n",
        "run_with_ngrok(se.app) \n",
        "se.app.run()"
      ],
      "metadata": {
        "id": "J5n9u9rFP_wD",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "6bb3bd05-82c9-4805-8e7d-ba1ad674a507"
      },
      "execution_count": 36,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            " * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            " * Running on http://feaa-34-105-121-176.ngrok.io\n",
            " * Traffic stats available on http://127.0.0.1:4040\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "[2022-01-12 11:44:49,562] ERROR in app: Exception on /search [GET]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n",
            "    reraise(exc_type, exc_value, tb)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n",
            "    raise value\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n",
            "    return self.view_functions[rule.endpoint](**req.view_args)\n",
            "  File \"/content/search_frontend.py\", line 765, in search\n",
            "    word_postings[Qword] = read_posting_list(index, Qword)\n",
            "  File \"/content/search_frontend.py\", line 575, in read_posting_list\n",
            "    b = reader.read(locs, index.df[w] * TUPLE_SIZE)\n",
            "  File \"/content/search_frontend.py\", line 545, in read\n",
            "    self._open_files[f_name] = open(f_name, 'rb')\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '97_010.bin'\n",
            "127.0.0.1 - - [12/Jan/2022 11:44:49] \"\u001b[35m\u001b[1mGET /search?query=python HTTP/1.1\u001b[0m\" 500 -\n",
            "[2022-01-12 11:44:49,674] ERROR in app: Exception on /search [GET]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n",
            "    reraise(exc_type, exc_value, tb)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n",
            "    raise value\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n",
            "    return self.view_functions[rule.endpoint](**req.view_args)\n",
            "  File \"/content/search_frontend.py\", line 765, in search\n",
            "    word_postings[Qword] = read_posting_list(index, Qword)\n",
            "  File \"/content/search_frontend.py\", line 575, in read_posting_list\n",
            "    b = reader.read(locs, index.df[w] * TUPLE_SIZE)\n",
            "  File \"/content/search_frontend.py\", line 545, in read\n",
            "    self._open_files[f_name] = open(f_name, 'rb')\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '108_011.bin'\n",
            "127.0.0.1 - - [12/Jan/2022 11:44:49] \"\u001b[35m\u001b[1mGET /search?query=data+science HTTP/1.1\u001b[0m\" 500 -\n",
            "[2022-01-12 11:44:49,786] ERROR in app: Exception on /search [GET]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n",
            "    reraise(exc_type, exc_value, tb)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n",
            "    raise value\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n",
            "    return self.view_functions[rule.endpoint](**req.view_args)\n",
            "  File \"/content/search_frontend.py\", line 765, in search\n",
            "    word_postings[Qword] = read_posting_list(index, Qword)\n",
            "  File \"/content/search_frontend.py\", line 575, in read_posting_list\n",
            "    b = reader.read(locs, index.df[w] * TUPLE_SIZE)\n",
            "  File \"/content/search_frontend.py\", line 545, in read\n",
            "    self._open_files[f_name] = open(f_name, 'rb')\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '70_015.bin'\n",
            "127.0.0.1 - - [12/Jan/2022 11:44:49] \"\u001b[35m\u001b[1mGET /search?query=migraine HTTP/1.1\u001b[0m\" 500 -\n",
            "[2022-01-12 11:44:49,895] ERROR in app: Exception on /search [GET]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n",
            "    reraise(exc_type, exc_value, tb)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n",
            "    raise value\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n",
            "    return self.view_functions[rule.endpoint](**req.view_args)\n",
            "  File \"/content/search_frontend.py\", line 765, in search\n",
            "    word_postings[Qword] = read_posting_list(index, Qword)\n",
            "  File \"/content/search_frontend.py\", line 575, in read_posting_list\n",
            "    b = reader.read(locs, index.df[w] * TUPLE_SIZE)\n",
            "  File \"/content/search_frontend.py\", line 545, in read\n",
            "    self._open_files[f_name] = open(f_name, 'rb')\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '59_011.bin'\n",
            "127.0.0.1 - - [12/Jan/2022 11:44:49] \"\u001b[35m\u001b[1mGET /search?query=chocolate HTTP/1.1\u001b[0m\" 500 -\n",
            "[2022-01-12 11:44:50,006] ERROR in app: Exception on /search [GET]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n",
            "    reraise(exc_type, exc_value, tb)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n",
            "    raise value\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n",
            "    return self.view_functions[rule.endpoint](**req.view_args)\n",
            "  File \"/content/search_frontend.py\", line 765, in search\n",
            "    word_postings[Qword] = read_posting_list(index, Qword)\n",
            "  File \"/content/search_frontend.py\", line 575, in read_posting_list\n",
            "    b = reader.read(locs, index.df[w] * TUPLE_SIZE)\n",
            "  File \"/content/search_frontend.py\", line 545, in read\n",
            "    self._open_files[f_name] = open(f_name, 'rb')\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '51_022.bin'\n",
            "127.0.0.1 - - [12/Jan/2022 11:44:50] \"\u001b[35m\u001b[1mGET /search?query=how+to+make+pasta HTTP/1.1\u001b[0m\" 500 -\n",
            "[2022-01-12 11:44:50,122] ERROR in app: Exception on /search [GET]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n",
            "    reraise(exc_type, exc_value, tb)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n",
            "    raise value\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n",
            "    return self.view_functions[rule.endpoint](**req.view_args)\n",
            "  File \"/content/search_frontend.py\", line 765, in search\n",
            "    word_postings[Qword] = read_posting_list(index, Qword)\n",
            "  File \"/content/search_frontend.py\", line 575, in read_posting_list\n",
            "    b = reader.read(locs, index.df[w] * TUPLE_SIZE)\n",
            "  File \"/content/search_frontend.py\", line 545, in read\n",
            "    self._open_files[f_name] = open(f_name, 'rb')\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '27_017.bin'\n",
            "127.0.0.1 - - [12/Jan/2022 11:44:50] \"\u001b[35m\u001b[1mGET /search?query=Does+pasta+have+preservatives%3F HTTP/1.1\u001b[0m\" 500 -\n",
            "[2022-01-12 11:44:50,233] ERROR in app: Exception on /search [GET]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n",
            "    reraise(exc_type, exc_value, tb)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n",
            "    raise value\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n",
            "    return self.view_functions[rule.endpoint](**req.view_args)\n",
            "  File \"/content/search_frontend.py\", line 765, in search\n",
            "    word_postings[Qword] = read_posting_list(index, Qword)\n",
            "  File \"/content/search_frontend.py\", line 575, in read_posting_list\n",
            "    b = reader.read(locs, index.df[w] * TUPLE_SIZE)\n",
            "  File \"/content/search_frontend.py\", line 545, in read\n",
            "    self._open_files[f_name] = open(f_name, 'rb')\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '84_000.bin'\n",
            "127.0.0.1 - - [12/Jan/2022 11:44:50] \"\u001b[35m\u001b[1mGET /search?query=how+google+works HTTP/1.1\u001b[0m\" 500 -\n",
            "[2022-01-12 11:44:50,346] ERROR in app: Exception on /search [GET]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n",
            "    reraise(exc_type, exc_value, tb)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n",
            "    raise value\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n",
            "    return self.view_functions[rule.endpoint](**req.view_args)\n",
            "  File \"/content/search_frontend.py\", line 765, in search\n",
            "    word_postings[Qword] = read_posting_list(index, Qword)\n",
            "  File \"/content/search_frontend.py\", line 575, in read_posting_list\n",
            "    b = reader.read(locs, index.df[w] * TUPLE_SIZE)\n",
            "  File \"/content/search_frontend.py\", line 545, in read\n",
            "    self._open_files[f_name] = open(f_name, 'rb')\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '11_024.bin'\n",
            "127.0.0.1 - - [12/Jan/2022 11:44:50] \"\u001b[35m\u001b[1mGET /search?query=what+is+information+retrieval HTTP/1.1\u001b[0m\" 500 -\n",
            "[2022-01-12 11:44:50,458] ERROR in app: Exception on /search [GET]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n",
            "    reraise(exc_type, exc_value, tb)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n",
            "    raise value\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n",
            "    return self.view_functions[rule.endpoint](**req.view_args)\n",
            "  File \"/content/search_frontend.py\", line 765, in search\n",
            "    word_postings[Qword] = read_posting_list(index, Qword)\n",
            "  File \"/content/search_frontend.py\", line 575, in read_posting_list\n",
            "    b = reader.read(locs, index.df[w] * TUPLE_SIZE)\n",
            "  File \"/content/search_frontend.py\", line 545, in read\n",
            "    self._open_files[f_name] = open(f_name, 'rb')\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '32_011.bin'\n",
            "127.0.0.1 - - [12/Jan/2022 11:44:50] \"\u001b[35m\u001b[1mGET /search?query=NBA HTTP/1.1\u001b[0m\" 500 -\n",
            "[2022-01-12 11:44:50,573] ERROR in app: Exception on /search [GET]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n",
            "    reraise(exc_type, exc_value, tb)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n",
            "    raise value\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n",
            "    return self.view_functions[rule.endpoint](**req.view_args)\n",
            "  File \"/content/search_frontend.py\", line 765, in search\n",
            "    word_postings[Qword] = read_posting_list(index, Qword)\n",
            "  File \"/content/search_frontend.py\", line 575, in read_posting_list\n",
            "    b = reader.read(locs, index.df[w] * TUPLE_SIZE)\n",
            "  File \"/content/search_frontend.py\", line 545, in read\n",
            "    self._open_files[f_name] = open(f_name, 'rb')\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '59_008.bin'\n",
            "127.0.0.1 - - [12/Jan/2022 11:44:50] \"\u001b[35m\u001b[1mGET /search?query=yoga HTTP/1.1\u001b[0m\" 500 -\n",
            "[2022-01-12 11:44:50,687] ERROR in app: Exception on /search [GET]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n",
            "    reraise(exc_type, exc_value, tb)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n",
            "    raise value\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n",
            "    return self.view_functions[rule.endpoint](**req.view_args)\n",
            "  File \"/content/search_frontend.py\", line 765, in search\n",
            "    word_postings[Qword] = read_posting_list(index, Qword)\n",
            "  File \"/content/search_frontend.py\", line 575, in read_posting_list\n",
            "    b = reader.read(locs, index.df[w] * TUPLE_SIZE)\n",
            "  File \"/content/search_frontend.py\", line 545, in read\n",
            "    self._open_files[f_name] = open(f_name, 'rb')\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '35_009.bin'\n",
            "127.0.0.1 - - [12/Jan/2022 11:44:50] \"\u001b[35m\u001b[1mGET /search?query=how+to+not+kill+plants HTTP/1.1\u001b[0m\" 500 -\n",
            "[2022-01-12 11:44:50,798] ERROR in app: Exception on /search [GET]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n",
            "    reraise(exc_type, exc_value, tb)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n",
            "    raise value\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n",
            "    return self.view_functions[rule.endpoint](**req.view_args)\n",
            "  File \"/content/search_frontend.py\", line 765, in search\n",
            "    word_postings[Qword] = read_posting_list(index, Qword)\n",
            "  File \"/content/search_frontend.py\", line 575, in read_posting_list\n",
            "    b = reader.read(locs, index.df[w] * TUPLE_SIZE)\n",
            "  File \"/content/search_frontend.py\", line 545, in read\n",
            "    self._open_files[f_name] = open(f_name, 'rb')\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '103_011.bin'\n",
            "127.0.0.1 - - [12/Jan/2022 11:44:50] \"\u001b[35m\u001b[1mGET /search?query=masks HTTP/1.1\u001b[0m\" 500 -\n",
            "[2022-01-12 11:44:50,908] ERROR in app: Exception on /search [GET]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n",
            "    reraise(exc_type, exc_value, tb)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n",
            "    raise value\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n",
            "    return self.view_functions[rule.endpoint](**req.view_args)\n",
            "  File \"/content/search_frontend.py\", line 765, in search\n",
            "    word_postings[Qword] = read_posting_list(index, Qword)\n",
            "  File \"/content/search_frontend.py\", line 575, in read_posting_list\n",
            "    b = reader.read(locs, index.df[w] * TUPLE_SIZE)\n",
            "  File \"/content/search_frontend.py\", line 545, in read\n",
            "    self._open_files[f_name] = open(f_name, 'rb')\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '35_018.bin'\n",
            "127.0.0.1 - - [12/Jan/2022 11:44:50] \"\u001b[35m\u001b[1mGET /search?query=black+friday HTTP/1.1\u001b[0m\" 500 -\n",
            "[2022-01-12 11:44:51,019] ERROR in app: Exception on /search [GET]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n",
            "    reraise(exc_type, exc_value, tb)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n",
            "    raise value\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n",
            "    return self.view_functions[rule.endpoint](**req.view_args)\n",
            "  File \"/content/search_frontend.py\", line 765, in search\n",
            "    word_postings[Qword] = read_posting_list(index, Qword)\n",
            "  File \"/content/search_frontend.py\", line 575, in read_posting_list\n",
            "    b = reader.read(locs, index.df[w] * TUPLE_SIZE)\n",
            "  File \"/content/search_frontend.py\", line 545, in read\n",
            "    self._open_files[f_name] = open(f_name, 'rb')\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '39_010.bin'\n",
            "127.0.0.1 - - [12/Jan/2022 11:44:51] \"\u001b[35m\u001b[1mGET /search?query=why+do+men+have+nipples HTTP/1.1\u001b[0m\" 500 -\n",
            "[2022-01-12 11:44:51,132] ERROR in app: Exception on /search [GET]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n",
            "    reraise(exc_type, exc_value, tb)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n",
            "    raise value\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n",
            "    return self.view_functions[rule.endpoint](**req.view_args)\n",
            "  File \"/content/search_frontend.py\", line 765, in search\n",
            "    word_postings[Qword] = read_posting_list(index, Qword)\n",
            "  File \"/content/search_frontend.py\", line 575, in read_posting_list\n",
            "    b = reader.read(locs, index.df[w] * TUPLE_SIZE)\n",
            "  File \"/content/search_frontend.py\", line 545, in read\n",
            "    self._open_files[f_name] = open(f_name, 'rb')\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '89_013.bin'\n",
            "127.0.0.1 - - [12/Jan/2022 11:44:51] \"\u001b[35m\u001b[1mGET /search?query=rubber+duck HTTP/1.1\u001b[0m\" 500 -\n",
            "[2022-01-12 11:44:51,244] ERROR in app: Exception on /search [GET]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n",
            "    reraise(exc_type, exc_value, tb)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n",
            "    raise value\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n",
            "    return self.view_functions[rule.endpoint](**req.view_args)\n",
            "  File \"/content/search_frontend.py\", line 765, in search\n",
            "    word_postings[Qword] = read_posting_list(index, Qword)\n",
            "  File \"/content/search_frontend.py\", line 575, in read_posting_list\n",
            "    b = reader.read(locs, index.df[w] * TUPLE_SIZE)\n",
            "  File \"/content/search_frontend.py\", line 545, in read\n",
            "    self._open_files[f_name] = open(f_name, 'rb')\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '54_013.bin'\n",
            "127.0.0.1 - - [12/Jan/2022 11:44:51] \"\u001b[35m\u001b[1mGET /search?query=michelin HTTP/1.1\u001b[0m\" 500 -\n",
            "[2022-01-12 11:44:51,356] ERROR in app: Exception on /search [GET]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n",
            "    reraise(exc_type, exc_value, tb)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n",
            "    raise value\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n",
            "    return self.view_functions[rule.endpoint](**req.view_args)\n",
            "  File \"/content/search_frontend.py\", line 765, in search\n",
            "    word_postings[Qword] = read_posting_list(index, Qword)\n",
            "  File \"/content/search_frontend.py\", line 575, in read_posting_list\n",
            "    b = reader.read(locs, index.df[w] * TUPLE_SIZE)\n",
            "  File \"/content/search_frontend.py\", line 545, in read\n",
            "    self._open_files[f_name] = open(f_name, 'rb')\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '34_010.bin'\n",
            "127.0.0.1 - - [12/Jan/2022 11:44:51] \"\u001b[35m\u001b[1mGET /search?query=what+to+watch HTTP/1.1\u001b[0m\" 500 -\n",
            "[2022-01-12 11:44:51,468] ERROR in app: Exception on /search [GET]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n",
            "    reraise(exc_type, exc_value, tb)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n",
            "    raise value\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n",
            "    return self.view_functions[rule.endpoint](**req.view_args)\n",
            "  File \"/content/search_frontend.py\", line 765, in search\n",
            "    word_postings[Qword] = read_posting_list(index, Qword)\n",
            "  File \"/content/search_frontend.py\", line 575, in read_posting_list\n",
            "    b = reader.read(locs, index.df[w] * TUPLE_SIZE)\n",
            "  File \"/content/search_frontend.py\", line 545, in read\n",
            "    self._open_files[f_name] = open(f_name, 'rb')\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '87_001.bin'\n",
            "127.0.0.1 - - [12/Jan/2022 11:44:51] \"\u001b[35m\u001b[1mGET /search?query=best+marvel+movie HTTP/1.1\u001b[0m\" 500 -\n",
            "[2022-01-12 11:44:51,579] ERROR in app: Exception on /search [GET]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n",
            "    reraise(exc_type, exc_value, tb)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n",
            "    raise value\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n",
            "    return self.view_functions[rule.endpoint](**req.view_args)\n",
            "  File \"/content/search_frontend.py\", line 765, in search\n",
            "    word_postings[Qword] = read_posting_list(index, Qword)\n",
            "  File \"/content/search_frontend.py\", line 575, in read_posting_list\n",
            "    b = reader.read(locs, index.df[w] * TUPLE_SIZE)\n",
            "  File \"/content/search_frontend.py\", line 545, in read\n",
            "    self._open_files[f_name] = open(f_name, 'rb')\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '41_022.bin'\n",
            "127.0.0.1 - - [12/Jan/2022 11:44:51] \"\u001b[35m\u001b[1mGET /search?query=how+tall+is+the+eiffel+tower HTTP/1.1\u001b[0m\" 500 -\n",
            "[2022-01-12 11:44:51,689] ERROR in app: Exception on /search [GET]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n",
            "    reraise(exc_type, exc_value, tb)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n",
            "    raise value\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n",
            "    return self.view_functions[rule.endpoint](**req.view_args)\n",
            "  File \"/content/search_frontend.py\", line 765, in search\n",
            "    word_postings[Qword] = read_posting_list(index, Qword)\n",
            "  File \"/content/search_frontend.py\", line 575, in read_posting_list\n",
            "    b = reader.read(locs, index.df[w] * TUPLE_SIZE)\n",
            "  File \"/content/search_frontend.py\", line 545, in read\n",
            "    self._open_files[f_name] = open(f_name, 'rb')\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '50_020.bin'\n",
            "127.0.0.1 - - [12/Jan/2022 11:44:51] \"\u001b[35m\u001b[1mGET /search?query=where+does+vanilla+flavoring+come+from HTTP/1.1\u001b[0m\" 500 -\n",
            "[2022-01-12 11:44:51,800] ERROR in app: Exception on /search [GET]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n",
            "    reraise(exc_type, exc_value, tb)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n",
            "    raise value\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n",
            "    return self.view_functions[rule.endpoint](**req.view_args)\n",
            "  File \"/content/search_frontend.py\", line 765, in search\n",
            "    word_postings[Qword] = read_posting_list(index, Qword)\n",
            "  File \"/content/search_frontend.py\", line 575, in read_posting_list\n",
            "    b = reader.read(locs, index.df[w] * TUPLE_SIZE)\n",
            "  File \"/content/search_frontend.py\", line 545, in read\n",
            "    self._open_files[f_name] = open(f_name, 'rb')\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '87_001.bin'\n",
            "127.0.0.1 - - [12/Jan/2022 11:44:51] \"\u001b[35m\u001b[1mGET /search?query=best+ice+cream+flavour HTTP/1.1\u001b[0m\" 500 -\n",
            "[2022-01-12 11:44:51,911] ERROR in app: Exception on /search [GET]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n",
            "    reraise(exc_type, exc_value, tb)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n",
            "    raise value\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n",
            "    return self.view_functions[rule.endpoint](**req.view_args)\n",
            "  File \"/content/search_frontend.py\", line 765, in search\n",
            "    word_postings[Qword] = read_posting_list(index, Qword)\n",
            "  File \"/content/search_frontend.py\", line 575, in read_posting_list\n",
            "    b = reader.read(locs, index.df[w] * TUPLE_SIZE)\n",
            "  File \"/content/search_frontend.py\", line 545, in read\n",
            "    self._open_files[f_name] = open(f_name, 'rb')\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '102_017.bin'\n",
            "127.0.0.1 - - [12/Jan/2022 11:44:51] \"\u001b[35m\u001b[1mGET /search?query=how+to+tie+a+tie HTTP/1.1\u001b[0m\" 500 -\n",
            "[2022-01-12 11:44:52,020] ERROR in app: Exception on /search [GET]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n",
            "    reraise(exc_type, exc_value, tb)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n",
            "    raise value\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n",
            "    return self.view_functions[rule.endpoint](**req.view_args)\n",
            "  File \"/content/search_frontend.py\", line 765, in search\n",
            "    word_postings[Qword] = read_posting_list(index, Qword)\n",
            "  File \"/content/search_frontend.py\", line 575, in read_posting_list\n",
            "    b = reader.read(locs, index.df[w] * TUPLE_SIZE)\n",
            "  File \"/content/search_frontend.py\", line 545, in read\n",
            "    self._open_files[f_name] = open(f_name, 'rb')\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '42_005.bin'\n",
            "127.0.0.1 - - [12/Jan/2022 11:44:52] \"\u001b[35m\u001b[1mGET /search?query=how+to+earn+money+online HTTP/1.1\u001b[0m\" 500 -\n",
            "[2022-01-12 11:44:52,130] ERROR in app: Exception on /search [GET]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n",
            "    reraise(exc_type, exc_value, tb)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n",
            "    raise value\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n",
            "    return self.view_functions[rule.endpoint](**req.view_args)\n",
            "  File \"/content/search_frontend.py\", line 765, in search\n",
            "    word_postings[Qword] = read_posting_list(index, Qword)\n",
            "  File \"/content/search_frontend.py\", line 575, in read_posting_list\n",
            "    b = reader.read(locs, index.df[w] * TUPLE_SIZE)\n",
            "  File \"/content/search_frontend.py\", line 545, in read\n",
            "    self._open_files[f_name] = open(f_name, 'rb')\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '8_010.bin'\n",
            "127.0.0.1 - - [12/Jan/2022 11:44:52] \"\u001b[35m\u001b[1mGET /search?query=what+is+critical+race+theory HTTP/1.1\u001b[0m\" 500 -\n",
            "[2022-01-12 11:44:52,243] ERROR in app: Exception on /search [GET]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n",
            "    reraise(exc_type, exc_value, tb)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n",
            "    raise value\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n",
            "    return self.view_functions[rule.endpoint](**req.view_args)\n",
            "  File \"/content/search_frontend.py\", line 765, in search\n",
            "    word_postings[Qword] = read_posting_list(index, Qword)\n",
            "  File \"/content/search_frontend.py\", line 575, in read_posting_list\n",
            "    b = reader.read(locs, index.df[w] * TUPLE_SIZE)\n",
            "  File \"/content/search_frontend.py\", line 545, in read\n",
            "    self._open_files[f_name] = open(f_name, 'rb')\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '119_018.bin'\n",
            "127.0.0.1 - - [12/Jan/2022 11:44:52] \"\u001b[35m\u001b[1mGET /search?query=what+space+movie+was+made+in+1992 HTTP/1.1\u001b[0m\" 500 -\n",
            "[2022-01-12 11:44:52,357] ERROR in app: Exception on /search [GET]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n",
            "    reraise(exc_type, exc_value, tb)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n",
            "    raise value\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n",
            "    return self.view_functions[rule.endpoint](**req.view_args)\n",
            "  File \"/content/search_frontend.py\", line 765, in search\n",
            "    word_postings[Qword] = read_posting_list(index, Qword)\n",
            "  File \"/content/search_frontend.py\", line 575, in read_posting_list\n",
            "    b = reader.read(locs, index.df[w] * TUPLE_SIZE)\n",
            "  File \"/content/search_frontend.py\", line 545, in read\n",
            "    self._open_files[f_name] = open(f_name, 'rb')\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '26_012.bin'\n",
            "127.0.0.1 - - [12/Jan/2022 11:44:52] \"\u001b[35m\u001b[1mGET /search?query=how+to+vote HTTP/1.1\u001b[0m\" 500 -\n",
            "[2022-01-12 11:44:52,470] ERROR in app: Exception on /search [GET]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n",
            "    reraise(exc_type, exc_value, tb)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n",
            "    raise value\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n",
            "    return self.view_functions[rule.endpoint](**req.view_args)\n",
            "  File \"/content/search_frontend.py\", line 765, in search\n",
            "    word_postings[Qword] = read_posting_list(index, Qword)\n",
            "  File \"/content/search_frontend.py\", line 575, in read_posting_list\n",
            "    b = reader.read(locs, index.df[w] * TUPLE_SIZE)\n",
            "  File \"/content/search_frontend.py\", line 545, in read\n",
            "    self._open_files[f_name] = open(f_name, 'rb')\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '84_000.bin'\n",
            "127.0.0.1 - - [12/Jan/2022 11:44:52] \"\u001b[35m\u001b[1mGET /search?query=google+trends HTTP/1.1\u001b[0m\" 500 -\n",
            "[2022-01-12 11:44:52,583] ERROR in app: Exception on /search [GET]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n",
            "    reraise(exc_type, exc_value, tb)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n",
            "    raise value\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n",
            "    return self.view_functions[rule.endpoint](**req.view_args)\n",
            "  File \"/content/search_frontend.py\", line 765, in search\n",
            "    word_postings[Qword] = read_posting_list(index, Qword)\n",
            "  File \"/content/search_frontend.py\", line 575, in read_posting_list\n",
            "    b = reader.read(locs, index.df[w] * TUPLE_SIZE)\n",
            "  File \"/content/search_frontend.py\", line 545, in read\n",
            "    self._open_files[f_name] = open(f_name, 'rb')\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '40_033.bin'\n",
            "127.0.0.1 - - [12/Jan/2022 11:44:52] \"\u001b[35m\u001b[1mGET /search?query=dim+sum HTTP/1.1\u001b[0m\" 500 -\n",
            "[2022-01-12 11:44:52,695] ERROR in app: Exception on /search [GET]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n",
            "    reraise(exc_type, exc_value, tb)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n",
            "    raise value\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n",
            "    return self.view_functions[rule.endpoint](**req.view_args)\n",
            "  File \"/content/search_frontend.py\", line 765, in search\n",
            "    word_postings[Qword] = read_posting_list(index, Qword)\n",
            "  File \"/content/search_frontend.py\", line 575, in read_posting_list\n",
            "    b = reader.read(locs, index.df[w] * TUPLE_SIZE)\n",
            "  File \"/content/search_frontend.py\", line 545, in read\n",
            "    self._open_files[f_name] = open(f_name, 'rb')\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '107_008.bin'\n",
            "127.0.0.1 - - [12/Jan/2022 11:44:52] \"\u001b[35m\u001b[1mGET /search?query=ted HTTP/1.1\u001b[0m\" 500 -\n",
            "[2022-01-12 11:44:52,807] ERROR in app: Exception on /search [GET]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n",
            "    reraise(exc_type, exc_value, tb)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n",
            "    raise value\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n",
            "    return self.view_functions[rule.endpoint](**req.view_args)\n",
            "  File \"/content/search_frontend.py\", line 765, in search\n",
            "    word_postings[Qword] = read_posting_list(index, Qword)\n",
            "  File \"/content/search_frontend.py\", line 575, in read_posting_list\n",
            "    b = reader.read(locs, index.df[w] * TUPLE_SIZE)\n",
            "  File \"/content/search_frontend.py\", line 545, in read\n",
            "    self._open_files[f_name] = open(f_name, 'rb')\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '73_007.bin'\n",
            "127.0.0.1 - - [12/Jan/2022 11:44:52] \"\u001b[35m\u001b[1mGET /search?query=fairy+tale HTTP/1.1\u001b[0m\" 500 -\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "# Testing your app\n",
        "\n",
        "Once your app is running you can query it. You can simply do that by navigating to the URL that ngrok gave you above or through code in a different python session. For example, once the frontend app is running, you can navigate to:\n",
        "http://YOUR_SERVER_DOMAIN/search?query=hello+world where YOUR_SERVER_DOMAIN is something like XXXX-XX-XX-XX-XX.ngrok.io, which is printed above in Colab or that is your external IP on GCP.\n",
        "\n",
        "The code below shows how to issue a query from python. This is also how our testing code will issue queries to your search engine, so make sure to test your search engine this way after you deploy it to GCP and before submission. Command line instructions for deploying your search engine to GCP are available at `run_frontend_in_gcp.sh`. Note that we will not only issue training queries to your search engine, but also test queries, i.e. queries that you've never seen before."
      ],
      "metadata": {
        "id": "Na0MC_1nzDbi"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "import json\n",
        "\n",
        "with open('queries_train.json', 'rt') as f:\n",
        "  queries = json.load(f)"
      ],
      "metadata": {
        "id": "EM5ePrRHojbG"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "def average_precision(true_list, predicted_list, k=40):\n",
        "    true_set = frozenset(true_list)\n",
        "    predicted_list = predicted_list[:k]\n",
        "    precisions = []\n",
        "    for i,doc_id in enumerate(predicted_list):        \n",
        "        if doc_id in true_set:\n",
        "            prec = (len(precisions)+1) / (i+1)            \n",
        "            precisions.append(prec)\n",
        "    if len(precisions) == 0:\n",
        "        return 0.0\n",
        "    return round(sum(precisions)/len(precisions),3)"
      ],
      "metadata": {
        "id": "gWimZWCOy3Ei"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "import requests\n",
        "from time import time\n",
        "# url = 'http://35.232.59.3:8080'\n",
        "# place the domain you got from ngrok or GCP IP below. \n",
        "url = 'http://XXXX-XX-XX-XX-XX.ngrok.io'\n",
        "\n",
        "qs_res = []\n",
        "for q, true_wids in queries.items():\n",
        "  duration, ap = None, None\n",
        "  t_start = time()\n",
        "  try:\n",
        "    res = requests.get(url + '/search', {'query': q}, timeout=35)\n",
        "    duration = time() - t_start\n",
        "    if res.status_code == 200:\n",
        "      pred_wids, _ = zip(*res.json())\n",
        "      ap = average_precision(true_wids, pred_wids)\n",
        "  except:\n",
        "    pass\n",
        "  \n",
        "  qs_res.append((q, duration, ap))"
      ],
      "metadata": {
        "id": "dYmNTq9u0ChK"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}